[build]
command = "hugo --minify"
publish = "public"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.107.0"

[context.deploy-preview]
command = "hugo --buildDrafts --buildFuture --minify"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
